apiVersion: apps/v1
kind: Deployment
metadata:
  name: subtractapp
  labels:
    app: subtract
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subtract
  template:
    metadata:
      labels:
        app: subtract
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "subtractapp"
        dapr.io/app-port: "1447"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: subtract
        image: ncolesummers72/distributed-calculator-deno:latest
        ports:
        - containerPort: 1447
        imagePullPolicy: Always